name: EverGuild
version: ${project.version}
main: fr.robotv2.guildconquest.main
api-version: 1.16
authors: [ Robotv2 ]
description: Un plugin de guilde et de conquête
commands:
  guild:
    description: main plugin command
