name: EverGuild
version: ${project.version}
main: fr.robotv2.guildconquest.main
api-version: 1.16
authors: [ Robotv2 ]
description: Un plugin de guilde
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
  - WorldGuardEvents
  - Citizens
  - WorldGuard
  - WorldEdit
  - MythicMobs
  - ProtocolLib
commands:
  guild:
    description: main plugin command
